### ISSUE TITLE
add new alarm programmatically with specific day 

### ISSUE THREAD

**Issue by ridhoaslam** [ataradov/alarm-me#8]
hi, how to add new alarm programmatically with specific day (eg. FRIDAY). thanks..!

    newAlarm = new Alarm();
                newAlarm.setId(2);
                newAlarm.setTitle("NEW ALARM IN FRIDAY");
                newAlarm.setDays(Calendar.FRIDAY);  //its not working correctly, I wanna set to friday only
                newAlarm.setDate(prayerTimes.dhuhr.getTime());
                mAlarmListAdapter.add(newAlarm);

**Comment by ataradov** [comment]
I really have no idea. This project is mostly abandoned since google  decided to make is super hard to actually make alarms that work. I'm not an android developer and I don't want to spend time investigating this.
